DROP TABLE IF EXISTS CompletedExerciseSets;

DROP TABLE IF EXISTS CompletedExerciseGroups;

DROP TABLE IF EXISTS CompletedWorkouts;

DROP TABLE IF EXISTS ExerciseSets;

DROP TABLE IF EXISTS ExerciseGroups;

DROP TABLE IF EXISTS Workouts;

DROP TABLE IF EXISTS Programs;

DROP TABLE IF EXISTS Exercises;

DROP TABLE IF EXISTS BodyParts;

DROP TABLE IF EXISTS Equipment;
