CREATE TABLE Programs (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL,
	Description VARCHAR(500)
)

CREATE TABLE Workouts (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Description VARCHAR(1000),
	Name VARCHAR(100) NOT NULL,
	ProgramId INT,
	FOREIGN KEY (ProgramId) REFERENCES Programs(Id)
		ON DELETE CASCADE
)

CREATE TABLE Muscles (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL,
	ColorRgb VARCHAR(10) NOT NULL
)

CREATE TABLE Equipment (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE SetTags (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL,
	ColorRgb VARCHAR(10) NOT NULL
)

CREATE TABLE Exercises (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL,
	Instructions VARCHAR(1000),
	Category VARCHAR(20) NOT NULL DEFAULT 'lift',
	EquipmentId INT NOT NULL,
	FOREIGN KEY (EquipmentId) REFERENCES Equipment(Id),
	CONSTRAINT CHK_Category CHECK(Category IN ('lift', 'timed', 'conditioning'))
)

CREATE TABLE ExercisesMuscles (
	Id INT PRIMARY KEY IDENTITY(1,1),
	ExerciseId INT NOT NULL,
	MuscleId INT NOT NULL,
	Weight INT NOT NULL DEFAULT 1,
	FOREIGN KEY (ExerciseId) REFERENCES Exercises(Id)
		ON DELETE CASCADE,
	FOREIGN KEY (MuscleId) REFERENCES Muscles(Id),
)

CREATE TABLE ExerciseGroups (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Note VARCHAR(500),
	RestTimeInSeconds INT,
	Sort INT NOT NULL,
	ExerciseId INT NOT NULL,
	WorkoutId INT NOT NULL,
	FOREIGN KEY (ExerciseId) REFERENCES Exercises(Id)
		ON DELETE CASCADE,
	FOREIGN KEY (WorkoutId) REFERENCES Workouts(Id)
		ON DELETE CASCADE
)

CREATE TABLE ExerciseSets (
	Id INT PRIMARY KEY IDENTITY(1,1),
	MinReps INT,
	MaxReps INT,
	SetTagId INT,
	Sort INT NOT NULL,
	ExerciseGroupId INT NOT NULL,
	FOREIGN KEY (ExerciseGroupId) REFERENCES ExerciseGroups(Id)
		ON DELETE CASCADE,
	FOREIGN KEY (SetTagId) REFERENCES SetTags(Id)
)

CREATE TABLE CompletedWorkouts (
	Id INT PRIMARY KEY IDENTITY(1,1),
	WorkoutId INT, -- NULLable because it might be an "empty workout"
	Name VARCHAR(100) NOT NULL,
	Description VARCHAR(1000),
	Note VARCHAR(500),
	DurationInSeconds INT NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (WorkoutId) REFERENCES Workouts(Id)
		ON DELETE SET NULL -- Do not DELETE if workout template is deleted
)

CREATE TABLE CompletedExerciseGroups (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Note VARCHAR(500),
	Comment VARCHAR(500),
	RestTimeInSeconds INT,
	Sort INT NOT NULL,
	ExerciseId INT NOT NULL,
	CompletedWorkoutId INT NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (ExerciseId) REFERENCES Exercises(Id)
		ON DELETE CASCADE,
	FOREIGN KEY (CompletedWorkoutId) REFERENCES CompletedWorkouts(Id)
		ON DELETE CASCADE
)

CREATE TABLE CompletedExerciseSets (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Reps INT NOT NULL,
	Weight FLOAT,
	MinReps INT,
	MaxReps INT,
	SetTagId INT,
	Sort INT NOT NULL,
	CompletedExerciseGroupId INT NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (CompletedExerciseGroupId) REFERENCES CompletedExerciseGroups(Id)
		ON DELETE CASCADE,
	FOREIGN KEY (SetTagId) REFERENCES SetTags(Id)
)