CREATE TABLE Programs (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL,
	Description VARCHAR(255)
)

CREATE TABLE Workouts (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL,
	ProgramId INT,
	FOREIGN KEY (ProgramId) REFERENCES Programs(Id)
		ON DELETE CASCADE
)

CREATE TABLE BodyParts (
	Id INT PRIMARY KEY IDENTITY(1,1),
	BodyPart VARCHAR(50) NOT NULL
)

CREATE TABLE Equipment (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Equipment VARCHAR(50) NOT NULL
)

CREATE TABLE Exercises (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL,
	Instructions VARCHAR(255),
	BodyPartId INT NOT NULL,
	EquipmentId INT NOT NULL,
	FOREIGN KEY (BodyPartId) REFERENCES BodyParts(Id),
	FOREIGN KEY (EquipmentId) REFERENCES Equipment(Id)
)

CREATE TABLE ExerciseGroups (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Note VARCHAR(255),
	Sort INT NOT NULL,
	ExerciseId INT NOT NULL,
	WorkoutId INT NOT NULL,
	FOREIGN KEY (ExerciseId) REFERENCES Exercises(Id)
		ON DELETE CASCADE,
	FOREIGN KEY (WorkoutId) REFERENCES Workouts(Id)
		ON DELETE CASCADE
)

CREATE TABLE ExerciseSets (
	Id INT PRIMARY KEY IDENTITY(1,1),
	MinReps INT,
	MaxReps INT,
	Weight FLOAT,
	Sort INT NOT NULL,
	ExerciseGroupId INT NOT NULL,
	FOREIGN KEY (ExerciseGroupId) REFERENCES ExerciseGroups(Id)
		ON DELETE CASCADE
)