INSERT INTO Exercises (Name, Instructions, Category, EquipmentId)
VALUES  ('Barbell Bench Press',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'barbell')),
		('Incline Dumbbell Bench Press',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'dumbbell')),
		('Pull-Up',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'body weight')),
		('Reverse Grip Pull-Up',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'body weight')),
		('Barbell Squat',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'barbell')),
		('Barbell Bent-Over Rows',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'barbell')),
		('Alternating Dumbbell Curls',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'dumbbell')),
		('Horizontal Machine Rows',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'machine')),
		('Dumbbell Shoulder Press',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'dumbbell')),
		('Crunch',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'body weight')),
		('Lat Machine Pull-Down',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'machine')),
		('Dumbbell Bench Rows',
			NULL,
			'lift',
			(SELECT Id FROM Equipment eq WHERE eq.Name = 'dumbbell'));

INSERT INTO ExercisesMuscles (ExerciseId, MuscleId, Weight)
VALUES (1,3,2),
	   (1,6,1),
	   (1,8,1),
	   (2,3,1),
	   (2,6,1),
	   (2,8,1),
	   (3,1,3),
	   (3,4,1),
	   (4,1,3),
	   (4,4,1),
	   (5,5,1),
	   (6,1,3),
	   (6,7,1),
	   (7,7,1),
	   (8,1,3),
	   (8,7,1),
	   (9,6,3),
	   (9,8,1),
	   (10,10,1),
	   (11,1,1),
	   (12,1,3),
	   (12,7,1);