INSERT INTO Exercises (Name, Instructions, BodyPartId, EquipmentId)
VALUES  ('Barbell Bench Press',
			NULL,
			(SELECT Id FROM BodyParts WHERE BodyPart = 'chest'),
			(SELECT Id FROM Equipment WHERE Equipment = 'barbell')),
		('Incline Dumbbell Bench Press',
			NULL,
			(SELECT Id FROM BodyParts WHERE BodyPart = 'chest'),
			(SELECT Id FROM Equipment WHERE Equipment = 'dumbbell')),
		('Pull-Up',
			NULL,
			(SELECT Id FROM BodyParts WHERE BodyPart = 'back'),
			(SELECT Id FROM Equipment WHERE Equipment = 'body weight')),
		('Reverse Grip Pull-Up',
			NULL,
			(SELECT Id FROM BodyParts WHERE BodyPart = 'back'),
			(SELECT Id FROM Equipment WHERE Equipment = 'body weight')),
		('Barbell Squat',
			NULL,
			(SELECT Id FROM BodyParts WHERE BodyPart = 'upper legs'),
			(SELECT Id FROM Equipment WHERE Equipment = 'barbell')),
		('Barbell Bent-Over Rows',
			NULL,
			(SELECT Id FROM BodyParts WHERE BodyPart = 'back'),
			(SELECT Id FROM Equipment WHERE Equipment = 'barbell')),
		('Alternating Dumbbell Curls',
			NULL,
			(SELECT Id FROM BodyParts WHERE BodyPart = 'biceps'),
			(SELECT Id FROM Equipment WHERE Equipment = 'dumbbell')),
		('Horizontal Machine Rows',
			NULL,
			(SELECT Id FROM BodyParts WHERE BodyPart = 'back'),
			(SELECT Id FROM Equipment WHERE Equipment = 'machine')),
		('Dumbbell Shoulder Press',
			NULL,
			(SELECT Id FROM BodyParts WHERE BodyPart = 'shoulders'),
			(SELECT Id FROM Equipment WHERE Equipment = 'barbell')),
		('Plank',
			NULL,
			(SELECT Id FROM BodyParts WHERE BodyPart = 'core'),
			(SELECT Id FROM Equipment WHERE Equipment = 'body weight'))