INSERT INTO Equipment (Name)
VALUES   ('assisted'),
		 ('band'),
		 ('barbell'),
		 ('body weight'),
		 ('cable'),
		 ('dumbbell'),
		 ('machine'),
		 ('ez barbell'),
		 ('kettlebell'),
		 ('medicine ball'),
		 ('resistance band'),
		 ('roller'),
		 ('rope'),
		 ('stability ball'),
		 ('trap bar'),
		 ('weighted')